services:
  dos:
    build:
      context: .
      args:
        SVARDOS_IMG_URL: ${SVARDOS_IMG_URL:-}
    image: ${DOS_IMAGE_NAME:-svarbox}
    container_name: ${DOS_CONTAINER_NAME:-svarbox}
    ports:
      - "${DOS_SSH_PORT:-2222}:22"
      - "${DOS_TELNET_PORT:-2323}:23"
      - "${DOS_HTTP_PORT:-8080}:${DOS_HTTP_PORT:-8080}"
    environment:
      DOS_ALLOW_MODE: ${DOS_ALLOW_MODE:-all}
      ENABLE_TELNET: ${ENABLE_TELNET:-1}
      TELNET_PORT: ${TELNET_PORT:-23}
      TELNET_LOGIN: /bin/login
      ENABLE_HTTP_CONSOLE: ${ENABLE_HTTP_CONSOLE:-1}
      DOS_HTTP_PORT: ${DOS_HTTP_PORT:-8080}
      DOS_HTTP_CRT: 0
    volumes:
      - ./allowed_repo:/opt/allowed_repo:z
      - ./config/dos_allowed:/etc/dos_allowed:ro,z
      - ./dos_env:/etc/dos_env:z
      - ./dos_home:/home/dosuser:z
      - ./dos_drives:/opt/dos_drives:z
    devices:
      - /dev/kvm:/dev/kvm
    restart: unless-stopped
